// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/a5932016/go-ddd-example/migration"
	"github.com/a5932016/go-ddd-example/repository/mysql"
	redis2 "github.com/a5932016/go-ddd-example/repository/redis"
	"github.com/a5932016/go-ddd-example/router"
	"github.com/a5932016/go-ddd-example/singleton/entity"
	"github.com/a5932016/go-ddd-example/singleton/entityUsecase"
	"github.com/a5932016/go-ddd-example/singleton/session"
	redis3 "github.com/a5932016/go-ddd-example/singleton/session/provider/redis"
	"github.com/a5932016/go-ddd-example/usecase"
	"github.com/redis/go-redis/v9"
	"github.com/spf13/afero"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitMigration init router
func InitMigration(mySqlC *gorm.DB) (migration.Migration, error) {
	v := _registerEntities()
	entityEntityHandler := entity.NewEntityHandler(mySqlC, v)
	dbRepository := mysql.NewDBRepository(mySqlC, entityEntityHandler)
	perRepository, err := perRepoProvider(mySqlC)
	if err != nil {
		return migration.Migration{}, err
	}
	migrationMigration := migration.New(dbRepository, perRepository)
	return migrationMigration, nil
}

// InitRouter init router
func InitRouter(appFs afero.Fs, mySqlC *gorm.DB, redisC2 *redis.Client) (router.Handler, error) {
	v := _registerEntities()
	entityEntityHandler := entity.NewEntityHandler(mySqlC, v)
	dbRepository := mysql.NewDBRepository(mySqlC, entityEntityHandler)
	memRepository, err := redis2.NewMemRepository(redisC2)
	if err != nil {
		return router.Handler{}, err
	}
	perRepository, err := perRepoProvider(mySqlC)
	if err != nil {
		return router.Handler{}, err
	}
	fsRepository := fsRepoProvider(appFs)
	maxLifeTime := _sessionRedisProviderMaxLifeTime()
	redisProvider := redis3.NewRedisProvider(memRepository, maxLifeTime)
	sessionName := _sessionRedisProviderSessionName()
	manager := session.NewManager(redisProvider, sessionName, maxLifeTime)
	modelPermissionsHandler, err := permissionsHandler()
	if err != nil {
		return router.Handler{}, err
	}
	handlerConstructor := usecase.NewHandler(dbRepository, memRepository, perRepository, fsRepository, manager, modelPermissionsHandler)
	entityUseCase := entityUsecase.NewEntityUseCase(dbRepository)
	handler := router.NewRouter(handlerConstructor, entityUseCase, memRepository, perRepository, manager)
	return handler, nil
}
