// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: filters_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Is         *string  `protobuf:"bytes,1,opt,name=is,proto3,oneof" json:"is,omitempty"`
	IsNot      *string  `protobuf:"bytes,2,opt,name=is_not,json=isNot,proto3,oneof" json:"is_not,omitempty"`
	StartsWith *string  `protobuf:"bytes,3,opt,name=starts_with,json=startsWith,proto3,oneof" json:"starts_with,omitempty"`
	EndWith    *string  `protobuf:"bytes,4,opt,name=end_with,json=endWith,proto3,oneof" json:"end_with,omitempty"`
	In         []string `protobuf:"bytes,5,rep,name=in,proto3" json:"in,omitempty"`
	NotIn      []string `protobuf:"bytes,6,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	Like       *string  `protobuf:"bytes,7,opt,name=like,proto3,oneof" json:"like,omitempty"`
	Likes      []string `protobuf:"bytes,8,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *StringFilter) Reset() {
	*x = StringFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFilter) ProtoMessage() {}

func (x *StringFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFilter.ProtoReflect.Descriptor instead.
func (*StringFilter) Descriptor() ([]byte, []int) {
	return file_filters_message_proto_rawDescGZIP(), []int{0}
}

func (x *StringFilter) GetIs() string {
	if x != nil && x.Is != nil {
		return *x.Is
	}
	return ""
}

func (x *StringFilter) GetIsNot() string {
	if x != nil && x.IsNot != nil {
		return *x.IsNot
	}
	return ""
}

func (x *StringFilter) GetStartsWith() string {
	if x != nil && x.StartsWith != nil {
		return *x.StartsWith
	}
	return ""
}

func (x *StringFilter) GetEndWith() string {
	if x != nil && x.EndWith != nil {
		return *x.EndWith
	}
	return ""
}

func (x *StringFilter) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *StringFilter) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *StringFilter) GetLike() string {
	if x != nil && x.Like != nil {
		return *x.Like
	}
	return ""
}

func (x *StringFilter) GetLikes() []string {
	if x != nil {
		return x.Likes
	}
	return nil
}

type BooleanFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Is        *bool `protobuf:"varint,1,opt,name=is,proto3,oneof" json:"is,omitempty"`
	IsPresent *bool `protobuf:"varint,2,opt,name=is_present,json=isPresent,proto3,oneof" json:"is_present,omitempty"`
}

func (x *BooleanFilter) Reset() {
	*x = BooleanFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanFilter) ProtoMessage() {}

func (x *BooleanFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanFilter.ProtoReflect.Descriptor instead.
func (*BooleanFilter) Descriptor() ([]byte, []int) {
	return file_filters_message_proto_rawDescGZIP(), []int{1}
}

func (x *BooleanFilter) GetIs() bool {
	if x != nil && x.Is != nil {
		return *x.Is
	}
	return false
}

func (x *BooleanFilter) GetIsPresent() bool {
	if x != nil && x.IsPresent != nil {
		return *x.IsPresent
	}
	return false
}

type SortFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asc  string `protobuf:"bytes,1,opt,name=asc,proto3" json:"asc,omitempty"`
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *SortFilter) Reset() {
	*x = SortFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortFilter) ProtoMessage() {}

func (x *SortFilter) ProtoReflect() protoreflect.Message {
	mi := &file_filters_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortFilter.ProtoReflect.Descriptor instead.
func (*SortFilter) Descriptor() ([]byte, []int) {
	return file_filters_message_proto_rawDescGZIP(), []int{2}
}

func (x *SortFilter) GetAsc() string {
	if x != nil {
		return x.Asc
	}
	return ""
}

func (x *SortFilter) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_filters_message_proto protoreflect.FileDescriptor

var file_filters_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a,
	0x06, 0x69, 0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x05, 0x69, 0x73, 0x4e, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x57, 0x69, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12,
	0x1e, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12,
	0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x6e, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x73, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x69, 0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e, 0x64, 0x5f,
	0x77, 0x69, 0x74, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x22, 0x5e, 0x0a,
	0x0d, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x13,
	0x0a, 0x02, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x02, 0x69, 0x73,
	0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x73, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x32, 0x0a,
	0x0a, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x73, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_message_proto_rawDescOnce sync.Once
	file_filters_message_proto_rawDescData = file_filters_message_proto_rawDesc
)

func file_filters_message_proto_rawDescGZIP() []byte {
	file_filters_message_proto_rawDescOnce.Do(func() {
		file_filters_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_message_proto_rawDescData)
	})
	return file_filters_message_proto_rawDescData
}

var file_filters_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_filters_message_proto_goTypes = []interface{}{
	(*StringFilter)(nil),  // 0: StringFilter
	(*BooleanFilter)(nil), // 1: BooleanFilter
	(*SortFilter)(nil),    // 2: SortFilter
}
var file_filters_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filters_message_proto_init() }
func file_filters_message_proto_init() {
	if File_filters_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooleanFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_filters_message_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_filters_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_message_proto_goTypes,
		DependencyIndexes: file_filters_message_proto_depIdxs,
		MessageInfos:      file_filters_message_proto_msgTypes,
	}.Build()
	File_filters_message_proto = out.File
	file_filters_message_proto_rawDesc = nil
	file_filters_message_proto_goTypes = nil
	file_filters_message_proto_depIdxs = nil
}
